name: Python CI Pipeline

on:
  push:
    branches:
      - main
    paths:
      - "covid19/**"
      - ".github/**"
  pull_request:
    branches:
      - main
    paths:
      - "covid19/**"
      - ".github/**"

jobs:
  py-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff

      - name: Run Ruff
        run: ruff check --output-format=github covid19/
